export const GET_INQUIRIES_START = "GET_INQUIRIES_START";
export const GET_INQUIRIES_END = "GET_INQUIRIES_END";
export const GET_INQUIRIES_SUCCESS = "GET_INQUIRIES_SUCCESS";
export const GET_INQUIRIES_FAILURE = "GET_INQUIRIES_FAILURE";
